In [3]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT name, SUM(cost) AS revenue
        FROM (SELECT Facilities.name, CASE WHEN Bookings.memid>0 THEN slots*membercost ELSE slots*guestcost END AS cost
            FROM `Bookings` 
            LEFT JOIN `Facilities` 
            USING (facid)
            LEFT JOIN `Members`
            USING (memid)) AS subquery
        GROUP BY name
        HAVING revenue < 1000
        ORDER BY revenue DESC;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Pool Table', 270)
('Snooker Table', 240)
('Table Tennis', 180)

In [4]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT p1.surname, p1.firstname, p2.surname AS Recsurname, p2.firstname AS Recfirstname
        FROM `Members` AS p1
        INNER JOIN `Members` AS p2
        ON p1.recommendedby = p2.memid
        ORDER BY p1.surname;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Bader', 'Florence', 'Stibbons', 'Ponder')
('Baker', 'Anne', 'Stibbons', 'Ponder')
('Baker', 'Timothy', 'Farrell', 'Jemima')
('Boothe', 'Tim', 'Rownam', 'Tim')
('Butters', 'Gerald', 'Smith', 'Darren')
('Coplin', 'Joan', 'Baker', 'Timothy')
('Crumpet', 'Erica', 'Smith', 'Tracy')
('Dare', 'Nancy', 'Joplette', 'Janice')
('Genting', 'Matthew', 'Butters', 'Gerald')
('Hunt', 'John', 'Purview', 'Millicent')
('Jones', 'David', 'Joplette', 'Janice')
('Jones', 'Douglas', 'Jones', 'David')
('Joplette', 'Janice', 'Smith', 'Darren')
('Mackenzie', 'Anna', 'Smith', 'Darren')
('Owen', 'Charles', 'Smith', 'Darren')
('Pinker', 'David', 'Farrell', 'Jemima')
('Purview', 'Millicent', 'Smith', 'Tracy')
('Rumney', 'Henrietta', 'Genting', 'Matthew')
('Sarwin', 'Ramnaresh', 'Bader', 'Florence')
('Smith', 'Jack', 'Smith', 'Darren')
('Stibbons', 'Ponder', 'Tracy', 'Burton')
('Worthington-Smyth', 'Henry', 'Smith', 'Tracy')

In [5]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT name, SUM(slots) AS usage_in_slots
        FROM (SELECT Bookings.facid, name, slots, memid
            FROM Bookings
            LEFT JOIN Facilities
            USING (facid)) AS subquery
        WHERE memid <>0
        GROUP BY name;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Badminton Court', 1086)
('Massage Room 1', 884)
('Massage Room 2', 54)
('Pool Table', 856)
('Snooker Table', 860)
('Squash Court', 418)
('Table Tennis', 794)
('Tennis Court 1', 957)
('Tennis Court 2', 882)

In [6]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT name, month, SUM(memslots) AS memusage_in_slots
        FROM (SELECT facid, name, SUBSTR(starttime, 1, 7) AS month, CASE WHEN memid<>0 THEN slots ELSE 0 END AS memslots
            FROM Bookings
            LEFT JOIN Facilities
            USING (facid)) AS subquery
        GROUP BY name, month;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Badminton Court', '2012-07', 165)
('Badminton Court', '2012-08', 414)
('Badminton Court', '2012-09', 507)
('Massage Room 1', '2012-07', 166)
('Massage Room 1', '2012-08', 316)
('Massage Room 1', '2012-09', 402)
('Massage Room 2', '2012-07', 8)
('Massage Room 2', '2012-08', 18)
('Massage Room 2', '2012-09', 28)
('Pool Table', '2012-07', 110)
('Pool Table', '2012-08', 303)
('Pool Table', '2012-09', 443)
('Snooker Table', '2012-07', 140)
('Snooker Table', '2012-08', 316)
('Snooker Table', '2012-09', 404)
('Squash Court', '2012-07', 50)
('Squash Court', '2012-08', 184)
('Squash Court', '2012-09', 184)
('Table Tennis', '2012-07', 98)
('Table Tennis', '2012-08', 296)
('Table Tennis', '2012-09', 400)
('Tennis Court 1', '2012-07', 201)
('Tennis Court 1', '2012-08', 339)
('Tennis Court 1', '2012-09', 417)
('Tennis Court 2', '2012-07', 123)
('Tennis Court 2', '2012-08', 345)
('Tennis Court 2', '2012-09', 414)